name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest # Using macOS since this is a macOS-specific package
    
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build
      run: pnpm build
      
    - name: Run tests
      run: pnpm test
      
    - name: Verify osascript is available
      run: which osascript
      
    - name: Test notification (basic)
      run: |
        pnpm start &
        sleep 2
        curl -X POST -H "Content-Type: application/json" -d '{"name":"send_notification","arguments":{"title":"CI Test","message":"Testing notifications from CI"}}' http://localhost:3000/rpc
